# Generated by Django 4.1.2 on 2022-10-10 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_category_options_alter_post_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostView',
            new_name='PostV',
        ),
    ]
